name: Renovate version updates

on:
  schedule:
    # Run on the first day of every month at 04:00 UTC
    - cron: '0 4 1 * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸš€ Job automatically triggered by ${{ github.event_name }}"
      - run: echo "ğŸ§ Job running on ${{ runner.os }} server"
      - run: echo "ğŸ™ Using ${{ github.ref }} branch from ${{ github.repository }} repository"

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          sparse-checkout: |
            .github
            deps.edn
      - run: echo "ğŸ™ ${{ github.repository }} repository was cloned to the runner."

      - name: Run Renovate
        uses: renovatebot/github-action@v44
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: info

      # Summary and status
      - run: echo "ğŸ¨ Renovate version update check completed"
      - run: echo "ğŸ Job status is ${{ job.status }}."
